### ISSUE TITLE
check the docker version to collect the correct column

### ISSUE THREAD

**Issue by wvoliveira** [pbabics/cmk-docker-services#1]
docker info | grep -i version:
Server Version: 18.03.1-ce
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Kernel Version: 4.16.0-0.bpo.1-amd64
WARNING: No swap limit support

When run this script cmk-docker-services/share/check_mk/agents/plugins/docker_service.sh it's collecting the wrong column in the variables "SERVICE_REPLICAS_RUNNING" and "SERVICE_REPLICAS_TOTAL" instead of take the number of 'replicas' are running, only take if the service is replicate.

In this version the column is 4th to grep number of replicas.

**Comment by pbabics** [comment]
Hello,

could you please post actual output so I can test it against something ? right now I don't have swarm initiated
